validation_file_path: ""
validation_file: ""

aws:
    region: "us-east-1"

putty:
    username: ""
    password: ""
  
reserve_tags_for_ec2:
  - "Name"
  - "Centrify"
  - "Description"
  - "RequestedBy"
  - "ProjectCode"
  - "SharedInfrastructure"
  - "ApplicationDeploymentCIID"
  - "CostCenterID"
  - "ProvisionType"
  - "env"
  - "costcodetype"
  - "project"
  - "organization"
  - "deploymenttype"
  - "PrimaryOwner"
  - "SecondaryOwner"
  - "osversion"
  - "ostype"
  - "platform"
  - "Morpheus Server Id"
  - "Morpheus Instance Id"
  - "Morpheus Id"
  - "vmw:provisioning:constraints.network"
  - "vmw:provisioning:deployment"
  - "vmw:provisioning:constraints.placement"
  - "vmw:provisioning:project"
  - "vmw:provisioning:flavorMapping"
  - "vmw:provisioning:imageMapping"
  - "az"
  - "vmw:provisioning:blueprintVersion"
  - "vmw:provisioning:org"
  - "vmw:provisioning:cloudZone"
  - "vmw:provisioning:requester"
  - "vmw:provisioning:blueprintResourceName"
  - "vmw:provisioning:constraints.storage"
  - "vmw:provisioning:blueprint"
  - "cloud_environment"
  - "dbversion"
  - "databasetype"
  - "region"
  - "DatabaseType"