name: EC2 Instance Validation

on:
  workflow_dispatch:

env:
  REGION: "us-east-1"  
  DEV_ROLE_ARN: "arn:aws:iam::992382823608:role/github-assumerole"
  INSTANCE_ID: ""
  S3_BUCKET_NAME: "test-j3"  # Replace with your S3 bucket name
  PYTHON_VERSION: "3.8"  # Parameterize your Python version

permissions:
  id-token: write
  contents: read

jobs:
  validate-instance:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Configure AWS Credentials for Dev
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ env.DEV_ROLE_ARN }}
        aws-region: ${{ env.REGION }}

    # - name: Fetch Latest EC2 Instance ID
    #   run: |
    #     instance_id=$(aws ec2 describe-instances --query 'Reservations[*].Instances[?State.Name==`running`].[InstanceId, LaunchTime]' --output text | sort -k2 -r | head -n 1 | awk '{print $1}')
    #     if [ -z "$instance_id" ]; then
    #       echo "No running instances found."
    #       exit 1
    #     fi
    #     echo "Latest Instance ID: $instance_id"
    #     echo "INSTANCE_ID=$instance_id" >> $GITHUB_ENV  # Set the instance ID as an environment variable

    # - name: Validate EC2 Instance Status
    #   run: |
    #     aws ec2 describe-instance-status --instance-ids ${{ env.INSTANCE_ID }} --output json

    - name: Run PuTTY Validation Script
      run: |
        report_path=$(python ./putty-validation.py "3.80.247.247")
        ls -la ./common
        cat ./common/aws_tags.json
      #  echo "PUTTY_REPORT_PATH=$report_path" >> $GITHUB_ENV  # Store report path
      continue-on-error: true

    - name: list dir
      run: |
        cat test.txt
        ls -la

    # - name: Gather Instance Details
    #   run: |
    #     report_path=$(python ./instance-details.py ${{ env.INSTANCE_ID }})
    #     echo "INSTANCE_REPORT_PATH=$report_path" >> $GITHUB_ENV  # Store report path
    

    # - name: Upload Putty Validation Report to S3
    #   run: |
    #     python ./reports-upload.py "${{ env.PUTTY_REPORT_PATH }}" "${{ env.S3_BUCKET_NAME }}"

    # - name: Upload Instance Details Report to S3
    #   run: |
    #     python ./upload_to_s3.py "${{ env.INSTANCE_REPORT_PATH }}" "${{ env.S3_BUCKET_NAME }}"

    # - name: Failure Notification
    #   if: failure()
    #   run: |
    #     echo "Validation failed for instance: ${{ env.INSTANCE_ID }} in environment: dev"
